export default [
  {
    ignores: ["node_modules/**", "images/**", "jenkins-pipeline-lab/**"],
  },
  js.configs.recommended,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.jest,
      },
    },
  },
];
